default_job = "test"

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_watch = ["src", "tests", "Cargo.toml", "Cargo.lock"]
need_stdout = true

[jobs.test-all]
command = ["cargo", "test", "--color", "always"]
need_watch = ["src", "tests", "Cargo.toml", "Cargo.lock"]
need_stdout = true

[jobs.just-test]
command = ["just", "test"]
need_watch = ["src", "tests", "Cargo.toml", "Cargo.lock", "justfile"]
need_stdout = true
